insert into dbo.especialidad (denominacion,editor_id) values ('Alergia e inmunología',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Alergia e inmunología pediátrica',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Anatomía patológica',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Anestesiología',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Angiología general y hemodinamia',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Bioquímica hematológica y hemostasia',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Bioquímica inmunológica',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Bioquímica microbiológica',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Bioquímica',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Cardiólogo',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Cardiólogo infantil',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Cirugía general',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Cirugía infantil',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Cirugía pediátrica',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Cirujano cardiovascular',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Cirujano cardiovascular pediátrica',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Cirugía vascular periférica',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Cirugía plástica y reparadora',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Cirugía de cabeza y cuello',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Cirugía de tórax',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Cirugía y traumatología buco máxilofacial',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Clinica médica',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Coloproctología',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Dermatología',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Dermatología pediátrica',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Diágnóstico por imágen',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Diágnóstico por imágen buco máxilofacial',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Electro fiosiología cardiaca',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Emergentología',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Endocrinólogía',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Endocrinólogía infantil',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Endodoncia',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Ecografista',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Farmacología clínica',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Fisiatría (medicina física y rehabilitación)',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Fonoaudiología',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Gastroenterología',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Gastroenterólogo infantil',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Genética médica',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Geriatría',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Ginecólogía',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Hematólogo infantil',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Hemoterapia e inmunohematología',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Hepatología',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Hepatología pediátrica',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Implantes y prótesis dentobucomaxilar',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Infectología',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Kinesiólogo',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Mastología',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Medicina del deporte',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Medicina del trabajo',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Medicina general y/o medicina de familia',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Medicina legal',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Medicina nuclear',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Medicina paliativa',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Medico clínico',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Nefrología',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Nefrólogo infantil',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Neonatología',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Neumonología',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Neumonólogo infantil',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Neurólogo',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Neurólogo infantil',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Nutrición',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Obstetricia',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Odontología general',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Odontopediatría',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Oftalmología',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Oncología',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Oncólogo infantil',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Ortodoncia y ortopedia maxilar',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Otorrinolaringología',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Pediatría',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Periodoncia',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Psicología',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Psicomotricidad',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Psicopedagogía',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Psiquiatría',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Psiquiatría infanto juvenil',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Radioterapia o terapia radiante',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Reumatología',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Reumatólogo infantil',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Terapia intensiva',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Terapia ocupacional',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Terapista intensivo infantil',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Tocoginecología',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Toxicología',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Traumatología',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Traumatología y ortopedia',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Traumatología y ortopedia infantil',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Urología',1);
