insert into dbo.especialidad (denominacion,editor_id) values ('Alergista',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Anatomo patólogo',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Anestesiólogo',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Cardiólogo',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Cirujano cardiovascular',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Cirugía general',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Cirujano',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Dermatólogo',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Endocrinólogo',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Fisiatra',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Fonoaudiología',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Gastroenterología',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Ginecólogo',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Hematólogo',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Infectología',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Kinesiólogo',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Ecografista',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Medico clínico',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Nefrología',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Neumonólogo',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Neurólogo',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Oftalmólogo',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Oncólogo',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Otorrinolaringólogo',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Traumatólogo',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Reumatólogo',1);
insert into dbo.especialidad (denominacion,editor_id) values ('Urólogo',1);
