-- INSERTS DE LA TABLA ESPECILIADES MEDICAS
insert into dbo.especialidad (denominacion) values ('Alergia e inmunología');
insert into dbo.especialidad (denominacion) values ('Alergia e inmunología pediátrica');
insert into dbo.especialidad (denominacion) values ('Anatomía patológica');
insert into dbo.especialidad (denominacion) values ('Anestesiólogía');
insert into dbo.especialidad (denominacion) values ('Angiología general y hemodinamia');
insert into dbo.especialidad (denominacion) values ('Bioquímica hematológica y hemostasia');
insert into dbo.especialidad (denominacion) values ('Bioquímica inmunológica');
insert into dbo.especialidad (denominacion) values ('Bioquímica microbiológica');
insert into dbo.especialidad (denominacion) values ('Bioquímica');
insert into dbo.especialidad (denominacion) values ('Cardiólogo');
insert into dbo.especialidad (denominacion) values ('Cardiólogo infantil');
insert into dbo.especialidad (denominacion) values ('Cirugía general');
insert into dbo.especialidad (denominacion) values ('Cirugía infantil');
insert into dbo.especialidad (denominacion) values ('Cirugía pediátrica');
insert into dbo.especialidad (denominacion) values ('Cirujano cardiovascular');
insert into dbo.especialidad (denominacion) values ('Cirujano cardiovascular pediátrica');
insert into dbo.especialidad (denominacion) values ('Cirugía vascular periférica');
insert into dbo.especialidad (denominacion) values ('Cirugía plástica y reparadora');
insert into dbo.especialidad (denominacion) values ('Cirugía de cabeza y cuello');
insert into dbo.especialidad (denominacion) values ('Cirugía de tórax');
insert into dbo.especialidad (denominacion) values ('Cirugía y traumatología buco máxilofacial');
insert into dbo.especialidad (denominacion) values ('Clinica médica');
insert into dbo.especialidad (denominacion) values ('Coloproctología');
insert into dbo.especialidad (denominacion) values ('Dermatología');
insert into dbo.especialidad (denominacion) values ('Dermatología pediátrica');
insert into dbo.especialidad (denominacion) values ('Diágnóstico por imágen');
insert into dbo.especialidad (denominacion) values ('Diágnóstico por imágen buco máxilofacial');
insert into dbo.especialidad (denominacion) values ('Electro fiosiología cardiaca');
insert into dbo.especialidad (denominacion) values ('Emergentología');
insert into dbo.especialidad (denominacion) values ('Endocrinólogía');
insert into dbo.especialidad (denominacion) values ('Endocrinólogía infantil');
insert into dbo.especialidad (denominacion) values ('Endodoncia');
insert into dbo.especialidad (denominacion) values ('Ecografista');
insert into dbo.especialidad (denominacion) values ('Farmacología clínica');
insert into dbo.especialidad (denominacion) values ('Fisiatría (medicina física y rehabilitación)');
insert into dbo.especialidad (denominacion) values ('Fonoaudiología');
insert into dbo.especialidad (denominacion) values ('Gastroenterología');
insert into dbo.especialidad (denominacion) values ('Gastroenterólogo infantil');
insert into dbo.especialidad (denominacion) values ('Genética médica');
insert into dbo.especialidad (denominacion) values ('Geriatría');
insert into dbo.especialidad (denominacion) values ('Ginecólogía');
insert into dbo.especialidad (denominacion) values ('Hematólogo infantil');
insert into dbo.especialidad (denominacion) values ('Hemoterapia e inmunohematología');
insert into dbo.especialidad (denominacion) values ('Hepatología');
insert into dbo.especialidad (denominacion) values ('Hepatología pediátrica');
insert into dbo.especialidad (denominacion) values ('Implantes y prótesis dentobucomaxilar');
insert into dbo.especialidad (denominacion) values ('Infectología');
insert into dbo.especialidad (denominacion) values ('Kinesiólogo');
insert into dbo.especialidad (denominacion) values ('Mastología');
insert into dbo.especialidad (denominacion) values ('Medicina del deporte');
insert into dbo.especialidad (denominacion) values ('Medicina del trabajo');
insert into dbo.especialidad (denominacion) values ('Medicina general y/o medicina de familia');
insert into dbo.especialidad (denominacion) values ('Medicina legal');
insert into dbo.especialidad (denominacion) values ('Medicina nuclear');
insert into dbo.especialidad (denominacion) values ('Medicina paliativa');
insert into dbo.especialidad (denominacion) values ('Medico clínico');
insert into dbo.especialidad (denominacion) values ('Nefrología');
insert into dbo.especialidad (denominacion) values ('Nefrólogo infantil');
insert into dbo.especialidad (denominacion) values ('Neonatología');
insert into dbo.especialidad (denominacion) values ('Neumonología');
insert into dbo.especialidad (denominacion) values ('Neumonólogo infantil');
insert into dbo.especialidad (denominacion) values ('Neurólogo');
insert into dbo.especialidad (denominacion) values ('Neurólogo infantil');
insert into dbo.especialidad (denominacion) values ('Nutrición');
insert into dbo.especialidad (denominacion) values ('Obstetricia');
insert into dbo.especialidad (denominacion) values ('Odontología general');
insert into dbo.especialidad (denominacion) values ('Odontopediatría');
insert into dbo.especialidad (denominacion) values ('Oftalmología');
insert into dbo.especialidad (denominacion) values ('Oncología');
insert into dbo.especialidad (denominacion) values ('Oncólogo infantil');
insert into dbo.especialidad (denominacion) values ('Ortodoncia y ortopedia maxilar');
insert into dbo.especialidad (denominacion) values ('Otorrinolaringología');
insert into dbo.especialidad (denominacion) values ('Pediatría');
insert into dbo.especialidad (denominacion) values ('Periodoncia');
insert into dbo.especialidad (denominacion) values ('Psicología');
insert into dbo.especialidad (denominacion) values ('Psicomotricidad');
insert into dbo.especialidad (denominacion) values ('Psicopedagogía');
insert into dbo.especialidad (denominacion) values ('Psiquiatría');
insert into dbo.especialidad (denominacion) values ('Psiquiatría infanto juvenil');
insert into dbo.especialidad (denominacion) values ('Radioterapia o terapia radiante');
insert into dbo.especialidad (denominacion) values ('Reumatología');
insert into dbo.especialidad (denominacion) values ('Reumatólogo infantil');
insert into dbo.especialidad (denominacion) values ('Terapia intensiva');
insert into dbo.especialidad (denominacion) values ('Terapia ocupacional');
insert into dbo.especialidad (denominacion) values ('Terapista intensivo infantil');
insert into dbo.especialidad (denominacion) values ('Tocoginecología');
insert into dbo.especialidad (denominacion) values ('Toxicología');
insert into dbo.especialidad (denominacion) values ('Traumatología');
insert into dbo.especialidad (denominacion) values ('Traumatología y ortopedia');
insert into dbo.especialidad (denominacion) values ('Traumatología y ortopedia infantil');
insert into dbo.especialidad (denominacion) values ('Urología');