//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consulta
    {
        public int Id { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Medico_Id { get; set; }
        public int Tipo_consulta_Id { get; set; }
        public int Paciente_Id { get; set; }
        public bool Pagada { get; set; }
    
        public virtual Persona_medico Persona_medico { get; set; }
        public virtual Persona_paciente Persona_paciente { get; set; }
        public virtual Tipo_consulta Tipo_consulta { get; set; }
    }
}
