//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Especialidad
    {
        public Especialidad()
        {
            this.Persona_medico = new HashSet<Persona_medico>();
        }
    
        public int Id { get; set; }
        public string Denominacion { get; set; }
        public int Editor_Id { get; set; }
    
        public virtual ICollection<Persona_medico> Persona_medico { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
