//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Obra_social
    {
        public Obra_social()
        {
            this.Consulta = new HashSet<Consulta>();
            this.Persona = new HashSet<Persona>();
        }
    
        public int Id { get; set; }
        public string Denominacion { get; set; }
        public decimal Plus { get; set; }
        public string Telefono { get; set; }
        public string Direccion { get; set; }
        public string Observaciones { get; set; }
    
        public virtual ICollection<Consulta> Consulta { get; set; }
        public virtual ICollection<Persona> Persona { get; set; }
    }
}
