//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona_medico
    {
        public Persona_medico()
        {
            this.Consulta = new HashSet<Consulta>();
            this.Especialidad = new HashSet<Especialidad>();
        }
    
        public string Matricula { get; set; }
        public int Id { get; set; }
    
        public virtual ICollection<Consulta> Consulta { get; set; }
        public virtual Persona Persona { get; set; }
        public virtual ICollection<Especialidad> Especialidad { get; set; }
    }
}
