//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personaobra_social
    {
        public int Obra_social_Id { get; set; }
        public int Persona_Id { get; set; }
        public Nullable<bool> orden_OS { get; set; }
        public Nullable<System.DateTime> fecha_vencimiento { get; set; }
    
        public virtual Obra_social Obra_social { get; set; }
        public virtual Persona Persona { get; set; }
    }
}
