//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        public Persona()
        {
            this.Consulta = new HashSet<Consulta>();
            this.Datos_contacto = new HashSet<Datos_contacto>();
            this.Obra_social = new HashSet<Obra_social>();
        }
    
        public int Id { get; set; }
        public string DNI { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public Nullable<int> Direccion_Id { get; set; }
        public string Sexo { get; set; }
        public int Editor_Id { get; set; }
    
        public virtual ICollection<Consulta> Consulta { get; set; }
        public virtual ICollection<Datos_contacto> Datos_contacto { get; set; }
        public virtual Direccion Direccion { get; set; }
        public virtual Persona_medico Persona_medico { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<Obra_social> Obra_social { get; set; }
    }
}
