//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Ciudad = new HashSet<Ciudad>();
            this.Consulta = new HashSet<Consulta>();
            this.Especialidad = new HashSet<Especialidad>();
            this.Feriado = new HashSet<Feriado>();
            this.Obra_social = new HashSet<Obra_social>();
            this.Persona = new HashSet<Persona>();
            this.Persona_medico = new HashSet<Persona_medico>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Password { get; set; }
        public string Nombre_completo { get; set; }
        public int Tipo_usuario_Id { get; set; }
    
        public virtual ICollection<Ciudad> Ciudad { get; set; }
        public virtual ICollection<Consulta> Consulta { get; set; }
        public virtual ICollection<Especialidad> Especialidad { get; set; }
        public virtual ICollection<Feriado> Feriado { get; set; }
        public virtual ICollection<Obra_social> Obra_social { get; set; }
        public virtual ICollection<Persona> Persona { get; set; }
        public virtual ICollection<Persona_medico> Persona_medico { get; set; }
        public virtual Tipo_usuario Tipo_usuario { get; set; }
    }
}
